### ISSUE TITLE
How Can This Work in PHP

### ISSUE THREAD

**Issue by developer4ATIT** [mygulamali/mumineen_calendar_js#1]
I am unable to find the init script for the PHP... Is it only for RUBY

**Comment by mygulamali** [comment]
Hi, this project is based on the [Middleman](https://middlemanapp.com/) static website generator, so there is no init script for PHP. Whilst Middleman is based on Ruby, the actual site is mostly in ReactJS and regular old HTML and SASS. Please see the source code for more information.
